USE DimitarIvanov

CREATE TABLE PET_OWNER1(
	OwnerID INT IDENTITY(1,1) NOT NULL UNIQUE,
	OwnerLastName VARCHAR(50) NOT NULL,
	OwnerFirstName VARCHAR(50) NOT NULL,
	OwnerPhone VARCHAR(50) UNIQUE,
	OwnerEmail VARCHAR(50) NOT NULL UNIQUE
)