USE DimitarIvanov

CREATE TABLE dbo.PET1(
	PetID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	PetName VARCHAR(50) NOT NULL,
	PetType VARCHAR(50) NOT NULL,
	PetBreed VARCHAR(50) NULL,
	PetDOB DATE,
	OwnerID INT NOT NULL,
	CONSTRAINT fk_pet1_petowner1 FOREIGN KEY (OwnerID) REFERENCES dbo.PET_OWNER1(OwnerID)
)